### ISSUE TITLE
[Task] Role Registration

### ISSUE THREAD

**Issue by alapha23** [alapha23/UrbanScholar#12]
## Description

Three roles
## `planner`
- Creates the project
- Goes through stages
Details refer to #9 

## `public`
- register
- read stages through a conversational interface

## `policy maker`
- read stages through a conversational interface
- generate reports, only in stage 5

## Tasks

Frontend
- [x] sign-in page redirects to role-selection if role unselected
- [x] Add role selection page
- [x] If choose planner/policy maker, prompt to enter invitation code to register either as a planner or a policy maker
    - [x] can go back to previous page
    - [x] click finish, then call "verify" API to verify the invitation code
    - [x] if verify passed, then call "role" API to save the role
    - [x] if verify failed, then show up a Red Alert message "Invalid Invitation Code"
- [x] If choose a general public person, prompt to the page of basic information, support skip/finish then jump to main page

Backend
- [x] New Backend Route "register"
- [x] New Backend API": "save_profile", "save_role", "verify"
- [x] Add Role, Profile to the DB
- [x] Add Profile Information to the DB

**Comment by alapha23** [comment]
#29
