### ISSUE TITLE
[Task] Planner Project Management

### ISSUE THREAD

**Issue by alapha23** [alapha23/UrbanScholar#30]
## Description

Planner can
1. create projects
2. view all created projects
3. select one of the projects
4. delete one of the projects

Each project has
1. 5 stages
2. A navigation bar on top that states which stage we are at
3. a conversational interface to facilitate report generation

## DB Design

```
table Project {
    id       String
    stage number
    title     String
    conversation1 Conversation?
    conversation2 Conversation?
    conversation3 Conversation?
    conversation4 Conversation?
    conversation5 Conversation?
}
```

## Tasks

Two pages 
1. View all projects of this planner
2. View one project

Frontend
- [x] create button, prompt user to enter title; then redirect to the project page
- [x] view all projects with their title
- [ ] view one project page has a nav bar that shows the project
- [x] view one project page has a conversation

Backend
- [x] API to create a project
- [ ] API to delete a project
- [x] API to fetch all projects of this planner
- [x] Each stage, the conversation is different, write a stub function for each stage conversation

**Comment by alapha23** [comment]
Core functionalities finished at
#31
