### ISSUE TITLE
[Task] Embed Conversations into stages

### ISSUE THREAD

**Issue by alapha23** [alapha23/UrbanScholar#32]
## Description

This issue specifically scopes down to the Planner scenarios, and will not support any feature for "citizen" nor "policy_maker", whose user flows are different from planners.

Conversations are used to articulate stage goals by the planners. Each stage has one conversation, the conversation serves as the medium to gather information so as to create a formal planning document goal statement, a report, or many others

For each stage, the information gathered from conversations will be passed on to the next one.

## Tasks

Frontend
- [ ] Whenever the user clicks next, if the next stage has never been created before, then create a new conversation, invoking chat.create API
- [ ] Embed viewable, interactable conversation within each page, note: each conversation has a different ID created from step 1
- [ ] When we switch the stages, switch the conversation accordingly

Backend
- [ ] Clicking the next button now creates one new conversation entry
- [ ] upon selecting a project, it will fetch all conversations of the current project, and will switch to the corresponding conversation after stage-switches
- [ ] upon creating a project, it will create a new conversation entry because it is a new stage (stage 1)
