### ISSUE TITLE
[Thread] Planner Superthread

### ISSUE THREAD

**Issue by alapha23** [alapha23/UrbanScholar#9]
# Scenarios

#### Assist writing Planning Document (~2 days)
- [x] Data analysis
- [ ] #7 (interpretation after analysis with academic contexts)
- [ ] #7 (guided update of data analysis results)
- [ ] #8 (Planning Document Upload, Fetch, Summaries)

#### Share Posts of the Planning Documents && Receive reviews

Documented in #11, tracked in #10

![image](https://github.com/alapha23/UrbanScholar/assets/23239892/8cc710f8-3f75-4932-8664-b6fafffe44bb)

4 knowledge base
a. academic knowledge base
b. planning documents
c. general documents e.g., wikipedia
d. datasets

All stages made by planners and policy makers are viewable to all users.

All stages by the public, are open through summaries.

From one stage to the next one, the result, the summary of all comments of the public, the summary of all comments of the policy maker, are passed to the next stage.

Stage 1 define problem + set goals (only able to be created by planner, commentable by all users)
QA + a,b,c

Stage 2 analyze data (for planners and public)
a,d

Stage 3 generate plan (planner)
b,c

Stage 4 evaluate plan (all user comment, planner make decision)
abc

Stage 5 choose plan (all user comment, planners make decision)
b,c

Stage 6 Implement plan / Report (planner+policy maker)
b,c

**Comment by alapha23** [comment]
Planner scenario
1. Reach their goal through a conversation
- every stage has a different goal
    - stage 1: define research problem & set goals, expect a document regarding what the project is about; No conversation needed; Full text readable by other roles
    - stage 2: analyze data: a. upload datasets b. validate size c. call chatgpt-4 to analyze and interpret
    - stage 3: Generate planning strategy: based on the knowledge base, propose planning strategy in response to stage 1 -- more about planning strategy rather than a report or a planning document; planner finalize a planning strategy
    - stage 4: Evaluate: a. planner comment and reflect on the result of stage 3; b. summarized automatically; c. planner evaluate outside of the system, finalize with an updated version of stage 3.
    - stage 5: Generate Report: a. planner use gpt to generate report,  based on stage 1, 2, 4, + knowledge base b + c, then refine the report conversationally, ; b. planner make viewable; c. policy maker comprehend + refine conversationally --> policy maker version


Policy maker scenario
stage 1: a. view document b. comprehend conversationally, with knowledge(abc) c. drop a comment 
stage 2: a. viewable datasets b. comprehend dataset conversationally c. drop comments
stage 3: planning strategy a., view planners' strategy, b. comprehend dataset conversationally 
stage 4: comprehend + drop comment 
stage 5: view, comprehend, refine, finalize: policy maker comprehend + refine conversationally --> policy maker version


Citizen scenario
stage 1: a. view document b. comprehend conversationally, with knowledge(abc) c. drop a comment 
stage 2: a. viewable datasets b. comprehend dataset conversationally c. drop comments
stage 3: planning strategy a., view planners' strategy, b. comprehend dataset conversationally 
stage 4: comprehend + drop comment 
stage 5: view, comprehend, comment
